targets:
  $default:
    builders:
      pheasantMainBuilder:
        options:
          entry: lib/App.phs
          sass: true
builders:
  pheasantMainBuilder:
    import: package:pheasant_build/src/build/builder.dart
    builder_factories:
      - pheasantMainBuilder
    build_extensions:
      $package$:
        - lib/main.phs.dart
    build_to: cache
    auto_apply: root_package
  pheasantFileBuilder:
    import: package:pheasant_build/src/build/builder.dart
    builder_factories:
      - pheasantFileBuilder
    build_extensions:
      .phs:
        - .phs.dart
    build_to: cache
    auto_apply: root_package