name: phse
description: A web app made with Pheasant.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  pheasant: ^0.1.0-alpha

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
