# Created with package:mono_repo v6.6.1
{
  "version": 2,
  "updates": [
    {
      "package-ecosystem": "github-actions",
      "directory": "/",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant_assets",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant_build",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant_cli",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant_meta",
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "pheasant_temp",
      "schedule": {
        "interval": "monthly"
      }
    }
  ]
}
