name: pheasant
description: >-
  The Pheasant Framework is a progressive, fast-reload, modern frontend web framework that allows you to make powerful web applications in Dart.
version: 0.1.0-grade
repository: https://github.com/pheasantframework/pheasant

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  pheasant_build: ^0.1.0-grade
  pheasant_temp: ^0.1.0-grade
  html: ^0.15.4

dev_dependencies:
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - pheasant
  - web
  - framework