// Copyright (c) 2024 The Pheasant Group. All Rights Reserved.
// Please see the AUTHORS files for more information.
// Intellectual property of third-party.
//
// This file, as well as use of the code in it, is governed by an MIT License
// that can be found in the LICENSE file.
// You may use this file only in accordance with the license.


import 'dart:html' show Element;

import 'routing/src/route.dart' as r;

import 'state/state.dart' show TemplateState, ElementState;

/// The base class for all Pheasant App Components
///
/// All Pheasant app components are derived from this base class, and are used to render pheasant code internally and return the desired html app component.
///
/// Every [PheasantTemplate] class instance has two main parts:
///
/// 1. The `template` field, which represents the pheasant template string that is to be rendered.
/// The [template] variable is of type [String] and is automatically overrided for every instance of this class from the `renderFunc` function
///
/// 2. The `render` function, which returns the rendered html element to be injected into the DOM.
/// The [render] function takes in one required parameter, the [template], and one optional parameter, [state].
/// There is no base definition of this function, as the definition of the function is generated by the `renderFunc` function.
///
/// Any other variables or functions defined in the `<script>` part of the `.phs` file, is added as normal fields and methods repsectively to the class.
///
/// Here is an instance of this class definition:
///
/// ```
/// class MyComponent extends PheasantTemplate {
///   @override
///   String? template = """
/// <div>
///   <p>Hello World</p>
/// </div>
/// """
///
///   PheasantTemplate({super.template});
///
///   @override
///   Element render(String temp) {
///     // Generated Code
///     return element;
///   }
/// }
/// ```
///
/// This class is not intended for direct usage, but mainly for implementation
abstract class PheasantTemplate {
  /// Fetches any parsed data from the previous component/page route as either a List or a Map.
  ///
  /// Casting can be done afterwards to get the desired outcome
  /// ```dart
  /// void init() {
  ///   dynamic data = fetchState();
  ///   if (data is Map) {
  ///     print(data['a']);
  ///   } else if (data is List) {
  ///     print(data[0]);
  ///   }
  /// }
  /// ```
  dynamic fetchState() => r.fetchState();

  /// Reloads the state of the component
  void reloadState([ElementState? state]) => state?.reload();

  /// Freeze the state of the component
  void freezeState([ElementState? state]) => state?.freeze();

  /// Unfreeze the state of the component
  void unfreezeState([ElementState? state]) => state?.unfreeze();

  /// Refresh the given page on the browser
  ///
  /// Does not achieve similar or the same effect as [reloadState].
  void refresh() => r.refreshPage();

  /// The `template` variable, which forms the html text body to be rendered.
  String? template;

  PheasantTemplate({required this.template});

  /// Function used to declare the initial state/case of a component.
  ///
  /// This function is called at the beginning of rendering, once the application is added to the DOM.
  ///
  /// [init] can be called synchronously or asynchronously.
  void init() async {}

  /// Function used to declare the final state of a component.
  /// This function is called at the end of the component's life cycle, either when removed from the DOM or navigating to another page
  void del() async {}

  /// The `render` function.
  ///
  /// This function accepts two parameters:
  /// `temp` which is of type [String] which represents the desired templating string to be rendered, and
  /// `state` which represents the state of the application, as a [TemplateState].
  ///
  /// The function returns a html element of type [Element].
  Element render(String temp, [TemplateState? state]);
}
