name: pheasant_build
description: >-
  The build package for all pheasant related compilation, as well as pheasant project configuration.
version: 0.1.0-dev.2
repository: https://github.com/pheasantframework/pheasant_build

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
  pheasant_temp: ^0.1.0-dev.1
  pheasant_meta: ^0.1.0-beta.1
  pheasant_assets: ^0.1.0-beta
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

topics:
  - pheasant
  - web