name: pheasant_cli
description: A sample command-line application with basic argument parsing.
version: 0.1.0-alpha
# repository: https://github.com/my_org/my_repo

executables:
  pheasant:

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_config: ^0.1.2
  cli_util: ^0.4.1
  io: ^1.0.4
  path: ^1.9.0
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
