name: pheasant_cli
description: The official cli for running, creating and working with Pheasant projects and applications.
version: 0.1.0-alpha.2
repository: https://github.com/pheasantframework/pheasant/pheasant_cli

executables:
  pheasant:

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.2
  cli_config: ^0.1.2
  cli_util: ^0.4.1
  io: ^1.0.4
  path: ^1.9.0
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
