# Created with package:mono_repo v6.6.1
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.6.1
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze; Dart 3.2.0; PKG: pheasant; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: pheasant; dart analyze
        run: dart analyze
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
  job_003:
    name: "analyze; Dart 3.2.0; PKG: pheasant; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: "pheasant; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
  job_004:
    name: "analyze; Dart 3.2.3; PKG: pheasant_cli; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.3"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: pheasant_cli; dart analyze
        run: dart analyze
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
  job_005:
    name: "analyze; Dart 3.2.3; PKG: pheasant_cli; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.3"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: "pheasant_cli; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
  job_006:
    name: "analyze; Dart dev; PKG: pheasant; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: pheasant; dart analyze
        run: dart analyze
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
  job_007:
    name: "analyze; Dart dev; PKG: pheasant_cli; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: pheasant_cli; dart analyze
        run: dart analyze
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
  job_008:
    name: "analyze; Dart dev; PKG: pheasant; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: "pheasant; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
  job_009:
    name: "analyze; Dart dev; PKG: pheasant_cli; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: "pheasant_cli; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
  job_010:
    name: "unit_test; Dart 3.2.0; PKG: pheasant; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: pheasant; dart test
        run: dart test
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
      - job_008
      - job_009
  job_011:
    name: "unit_test; Dart 3.2.3; PKG: pheasant_cli; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:3.2.3
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: "3.2.3"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: pheasant_cli; dart test
        run: dart test
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
      - job_008
      - job_009
  job_012:
    name: "unit_test; Dart dev; PKG: pheasant; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_pub_upgrade
        name: pheasant; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant
      - name: pheasant; dart test
        run: dart test
        if: "always() && steps.pheasant_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
      - job_008
      - job_009
  job_013:
    name: "unit_test; Dart dev; PKG: pheasant_cli; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pheasant_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - id: pheasant_cli_pub_upgrade
        name: pheasant_cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pheasant_cli
      - name: pheasant_cli; dart test
        run: dart test
        if: "always() && steps.pheasant_cli_pub_upgrade.conclusion == 'success'"
        working-directory: pheasant_cli
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
      - job_007
      - job_008
      - job_009
